#include "common_dbc.h"

namespace {

const Signal sigs_2564485392[] = {
    {
      .name = "length",
      .b1 = 0,
      .b2 = 8,
      .bo = 56,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "service",
      .b1 = 12,
      .b2 = 4,
      .bo = 48,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "response",
      .b1 = 8,
      .b2 = 4,
      .bo = 52,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ParameterID_Service01",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "ParameterID_Service02",
      .b1 = 16,
      .b2 = 8,
      .bo = 40,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_00_PIDsSupported_01_20",
      .b1 = 24,
      .b2 = 32,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_01_MonitorStatus",
      .b1 = 24,
      .b2 = 32,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_02_FreezeDTC",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_03_FuelSystemStatus",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_04_CalcEngineLoad",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.39216,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_05_EngineCoolantTemp",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = -40.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_06_ShortFuelTrimBank1",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.78125,
      .offset = -100.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_07_LongFuelTrimBank1",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.78125,
      .offset = -100.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_08_ShortFuelTrimBank2",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.78125,
      .offset = -100.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_09_LongFuelTrimBank2",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.78125,
      .offset = -100.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_0A_FuelPressure",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 3,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_0B_IntakeManiAbsPress",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_0C_EngineRPM",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 0.25,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_0D_VehicleSpeed",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_0E_TimingAdvance",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.5,
      .offset = -64.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_0F_IntakeAirTemperature",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = -40.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_10_MAFAirFlowRate",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 0.01,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_11_ThrottlePosition",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.39216,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_12_CmdSecAirStatus",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_14_OxySensor1_Volt",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.005,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_15_OxySensor2_Volt",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.005,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_16_OxySensor3_Volt",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.005,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_17_OxySensor4_Volt",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.005,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_18_OxySensor5_Volt",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.005,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_19_OxySensor6_Volt",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.005,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_1A_OxySensor7_Volt",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.005,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_1B_OxySensor8_Volt",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.005,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_1C_OBDStandard",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_1F_TimeSinceEngStart",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_20_PIDsSupported_21_40",
      .b1 = 24,
      .b2 = 32,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_21_DistanceMILOn",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_22_FuelRailPres",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 0.079,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_23_FuelRailGaug",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 10,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_24_OxySensor1_FAER",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 3.0517578125e-05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_25_OxySensor2_FAER",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 3.0517578125e-05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_26_OxySensor3_FAER",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 3.0517578125e-05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_27_OxySensor4_FAER",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 3.0517578125e-05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_28_OxySensor5_FAER",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 3.0517578125e-05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_29_OxySensor6_FAER",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 3.0517578125e-05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_2A_OxySensor7_FAER",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 3.0517578125e-05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_2B_OxySensor8_FAER",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 3.0517578125e-05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_2C_CmdEGR",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.39215686275,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_2D_EGRError",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.78125,
      .offset = -100.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_2E_CmdEvapPurge",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.39215686275,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_2F_FuelTankLevel",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.39215686275,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_30_WarmUpsSinceCodeClear",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_31_DistanceSinceCodeClear",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_32_EvapSysVaporPres",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = true,
      .factor = 0.25,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_33_AbsBaroPres",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_34_OxySensor1_FAER",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 3.0517578125e-05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_35_OxySensor2_FAER",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 3.0517578125e-05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_36_OxySensor3_FAER",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 3.0517578125e-05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_37_OxySensor4_FAER",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 3.0517578125e-05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_38_OxySensor5_FAER",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 3.0517578125e-05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_39_OxySensor6_FAER",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 3.0517578125e-05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_3A_OxySensor7_FAER",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 3.0517578125e-05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_3B_OxySensor8_FAER",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 3.0517578125e-05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_3C_CatTempBank1Sens1",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 0.1,
      .offset = -40.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_3D_CatTempBank2Sens1",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 0.1,
      .offset = -40.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_3E_CatTempBank1Sens2",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 0.1,
      .offset = -40.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_3F_CatTempBank2Sens2",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 0.1,
      .offset = -40.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_40_PIDsSupported_41_60",
      .b1 = 24,
      .b2 = 32,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_41_MonStatusDriveCycle",
      .b1 = 24,
      .b2 = 32,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_42_ControlModuleVolt",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 0.001,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_43_AbsLoadValue",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 0.39215686275,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_44_FuelAirCmdEquiv",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 3.0517578125e-05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_45_RelThrottlePos",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.39215686275,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_46_AmbientAirTemp",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = -40.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_47_AbsThrottlePosB",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.39215686275,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_48_AbsThrottlePosC",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.39215686275,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_49_AbsThrottlePosD",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.39215686275,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_4A_AbsThrottlePosE",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.39215686275,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_4B_AbsThrottlePosF",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.39215686275,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_4C_CmdThrottleAct",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.39215686275,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_4D_TimeRunMILOn",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_4E_TimeSinceCodeClear",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_4F_Max_FAER",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_50_Max_AirFlowMAF",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 10,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_51_FuelType",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_52_EthanolFuelPct",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.39215686275,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_53_AbsEvapSysVapPres",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 0.005,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_54_EvapSysVapPres",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = -32767.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_55_ShortSecOxyTrimBank1",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.78125,
      .offset = -100.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_56_LongSecOxyTrimBank1",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.78125,
      .offset = -100.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_57_ShortSecOxyTrimBank2",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.78125,
      .offset = -100.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_58_LongSecOxyTrimBank2",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.78125,
      .offset = -100.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_59_FuelRailAbsPres",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 10,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_5A_RelAccelPedalPos",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.39215686275,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_5B_HybrBatPackRemLife",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 0.39215686275,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_5C_EngineOilTemp",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = -40.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_5D_FuelInjectionTiming",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 0.0078125,
      .offset = -210.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_5E_EngineFuelRate",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 0.05,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_5F_EmissionReq",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_60_PIDsSupported_61_80",
      .b1 = 24,
      .b2 = 32,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_61_DemandEngTorqPct",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = -125.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_62_ActualEngTorqPct",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = -125.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_63_EngRefTorq",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_64_EngPctTorq_Idle",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = -125.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_65_AuxInputOutput",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_66_MAFSensor",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_67_EngineCoolantTemp",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_68_IntakeAirTempSens",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_69_CmdEGR_EGRError",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_6A_CmdDieselIntAir",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_6B_ExhaustGasTemp",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_6C_CmdThrottleActRel",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_6D_FuelPresContrSys",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_6E_InjPresContrSys",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_6F_TurboComprPres",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_70_BoostPresCntrl",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_80_PIDsSupported_81_A0",
      .b1 = 24,
      .b2 = 32,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_8E_EngFrictionPctTorq",
      .b1 = 24,
      .b2 = 8,
      .bo = 32,
      .is_signed = false,
      .factor = 1,
      .offset = -125.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_A0_PIDsSupported_A1_C0",
      .b1 = 24,
      .b2 = 32,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_C0_PIDsSupported_C1_E0",
      .b1 = 24,
      .b2 = 32,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S2_PID_02_FreezeDTC",
      .b1 = 24,
      .b2 = 16,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_14_OxySensor1_STFT",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 0.78125,
      .offset = -100.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_15_OxySensor2_STFT",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 0.78125,
      .offset = -100.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_16_OxySensor3_STFT",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 0.78125,
      .offset = -100.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_17_OxySensor4_STFT",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 0.78125,
      .offset = -100.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_18_OxySensor5_STFT",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 0.78125,
      .offset = -100.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_19_OxySensor6_STFT",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 0.78125,
      .offset = -100.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_1A_OxySensor7_STFT",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 0.78125,
      .offset = -100.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_1B_OxySensor8_STFT",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 0.78125,
      .offset = -100.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_4F_Max_OxySensVol",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_55_ShortSecOxyTrimBank3",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 0.78125,
      .offset = -100.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_56_LongSecOxyTrimBank3",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 0.78125,
      .offset = -100.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_57_ShortSecOxyTrimBank4",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 0.78125,
      .offset = -100.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_58_LongSecOxyTrimBank4",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 0.78125,
      .offset = -100.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_64_EngPctTorq_EP1",
      .b1 = 32,
      .b2 = 8,
      .bo = 24,
      .is_signed = false,
      .factor = 1,
      .offset = -125.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_24_OxySensor1_Volt",
      .b1 = 40,
      .b2 = 16,
      .bo = 8,
      .is_signed = false,
      .factor = 0.0001220703125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_25_OxySensor2_Volt",
      .b1 = 40,
      .b2 = 16,
      .bo = 8,
      .is_signed = false,
      .factor = 0.0001220703125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_26_OxySensor3_Volt",
      .b1 = 40,
      .b2 = 16,
      .bo = 8,
      .is_signed = false,
      .factor = 0.0001220703125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_27_OxySensor4_Volt",
      .b1 = 40,
      .b2 = 16,
      .bo = 8,
      .is_signed = false,
      .factor = 0.0001220703125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_28_OxySensor5_Volt",
      .b1 = 40,
      .b2 = 16,
      .bo = 8,
      .is_signed = false,
      .factor = 0.0001220703125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_29_OxySensor6_Volt",
      .b1 = 40,
      .b2 = 16,
      .bo = 8,
      .is_signed = false,
      .factor = 0.0001220703125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_2A_OxySensor7_Volt",
      .b1 = 40,
      .b2 = 16,
      .bo = 8,
      .is_signed = false,
      .factor = 0.0001220703125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_2B_OxySensor8_Volt",
      .b1 = 40,
      .b2 = 16,
      .bo = 8,
      .is_signed = false,
      .factor = 0.0001220703125,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_34_OxySensor1_Crnt",
      .b1 = 40,
      .b2 = 16,
      .bo = 8,
      .is_signed = false,
      .factor = 0.00390625,
      .offset = -128.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_35_OxySensor2_Crnt",
      .b1 = 40,
      .b2 = 16,
      .bo = 8,
      .is_signed = false,
      .factor = 0.00390625,
      .offset = -128.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_36_OxySensor3_Crnt",
      .b1 = 40,
      .b2 = 16,
      .bo = 8,
      .is_signed = false,
      .factor = 0.00390625,
      .offset = -128.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_37_OxySensor4_Crnt",
      .b1 = 40,
      .b2 = 16,
      .bo = 8,
      .is_signed = false,
      .factor = 0.00390625,
      .offset = -128.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_38_OxySensor5_Crnt",
      .b1 = 40,
      .b2 = 16,
      .bo = 8,
      .is_signed = false,
      .factor = 0.00390625,
      .offset = -128.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_39_OxySensor6_Crnt",
      .b1 = 40,
      .b2 = 16,
      .bo = 8,
      .is_signed = false,
      .factor = 0.00390625,
      .offset = -128.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_3A_OxySensor7_Crnt",
      .b1 = 40,
      .b2 = 16,
      .bo = 8,
      .is_signed = false,
      .factor = 0.00390625,
      .offset = -128.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_3B_OxySensor8_Crnt",
      .b1 = 40,
      .b2 = 16,
      .bo = 8,
      .is_signed = false,
      .factor = 0.00390625,
      .offset = -128.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_4F_Max_OxySensCrnt",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_64_EngPctTorq_EP2",
      .b1 = 40,
      .b2 = 8,
      .bo = 16,
      .is_signed = false,
      .factor = 1,
      .offset = -125.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_4F_Max_IntManiAbsPres",
      .b1 = 48,
      .b2 = 8,
      .bo = 8,
      .is_signed = false,
      .factor = 10,
      .offset = 0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_64_EngPctTorq_EP3",
      .b1 = 48,
      .b2 = 8,
      .bo = 8,
      .is_signed = false,
      .factor = 1,
      .offset = -125.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
    {
      .name = "S1_PID_64_EngPctTorq_EP4",
      .b1 = 56,
      .b2 = 8,
      .bo = 0,
      .is_signed = false,
      .factor = 1,
      .offset = -125.0,
      .is_little_endian = false,
      .type = SignalType::DEFAULT,
    },
};

const Msg msgs[] = {
  {
    .name = "OBD2",
    .address = 0x98DAF110,
    .size = 8,
    .num_sigs = ARRAYSIZE(sigs_2564485392),
    .sigs = sigs_2564485392,
  },
};

const Val vals[] = {
    {
      .name = "ParameterID_Service01",
      .address = 0x98DAF110,
      .def_val = "0 S1_PID_00_PIDSSUPPORTED_01_20 1 S1_PID_01_MONITORSTATUS 2 S1_PID_02_FREEZEDTC 3 S1_PID_03_FUELSYSTEMSTATUS 4 S1_PID_04_CALCENGINELOAD 5 S1_PID_05_ENGINECOOLANTTEMP 6 S1_PID_06_SHORTFUELTRIMBANK1 7 S1_PID_07_LONGFUELTRIMBANK1 8 S1_PID_08_SHORTFUELTRIMBANK2 9 S1_PID_09_LONGFUELTRIMBANK2 10 S1_PID_0A_FUELPRESSURE 11 S1_PID_0B_INTAKEMANIABSPRESS 12 S1_PID_0C_ENGINERPM 13 S1_PID_0D_VEHICLESPEED 14 S1_PID_0E_TIMINGADVANCE 15 S1_PID_0F_INTAKEAIRTEMPERATURE 16 S1_PID_10_MAFAIRFLOWRATE 17 S1_PID_11_THROTTLEPOSITION 18 S1_PID_12_CMDSECAIRSTATUS 20 S1_PID_14_OXYSENSOR1 21 S1_PID_15_OXYSENSOR2 22 S1_PID_16_OXYSENSOR3 23 S1_PID_17_OXYSENSOR4 24 S1_PID_18_OXYSENSOR5 25 S1_PID_19_OXYSENSOR6 26 S1_PID_1A_OXYSENSOR7 27 S1_PID_1B_OXYSENSOR8 28 S1_PID_1C_OBDSTANDARD 31 S1_PID_1F_TIMESINCEENGSTART 32 S1_PID_20_PIDSSUPPORTED_21_40 33 S1_PID_21_DISTANCEMILON 34 S1_PID_22_FUELRAILPRES 35 S1_PID_23_FUELRAILGAUG 36 S1_PID_24_OXYSENSOR1 37 S1_PID_25_OXYSENSOR2 38 S1_PID_26_OXYSENSOR3 39 S1_PID_27_OXYSENSOR4 40 S1_PID_28_OXYSENSOR5 41 S1_PID_29_OXYSENSOR6 42 S1_PID_2A_OXYSENSOR7 43 S1_PID_2B_OXYSENSOR8 44 S1_PID_2C_CMDEGR 45 S1_PID_2D_EGRERROR 46 S1_PID_2E_CMDEVAPPURGE 47 S1_PID_2F_FUELTANKLEVEL 48 S1_PID_30_WARMUPSSINCECODECLEAR 49 S1_PID_31_DISTANCESINCECODECLEAR 50 S1_PID_32_EVAPSYSVAPORPRES 51 S1_PID_33_ABSBAROPRES 52 S1_PID_34_OXYSENSOR1 53 S1_PID_35_OXYSENSOR2 54 S1_PID_36_OXYSENSOR3 55 S1_PID_37_OXYSENSOR4 56 S1_PID_38_OXYSENSOR5 57 S1_PID_39_OXYSENSOR6 58 S1_PID_3A_OXYSENSOR7 59 S1_PID_3B_OXYSENSOR8 60 S1_PID_3C_CATTEMPBANK1SENS1 61 S1_PID_3D_CATTEMPBANK2SENS1 62 S1_PID_3E_CATTEMPBANK1SENS2 63 S1_PID_3F_CATTEMPBANK2SENS2 64 S1_PID_40_PIDSSUPPORTED_41_60 65 S1_PID_41_MONSTATUSDRIVECYCLE 66 S1_PID_42_CONTROLMODULEVOLT 67 S1_PID_43_ABSLOADVALUE 68 S1_PID_44_FUELAIRCMDEQUIV 69 S1_PID_45_RELTHROTTLEPOS 70 S1_PID_46_AMBIENTAIRTEMP 71 S1_PID_47_ABSTHROTTLEPOSB 72 S1_PID_48_ABSTHROTTLEPOSC 73 S1_PID_49_ABSTHROTTLEPOSD 74 S1_PID_4A_ABSTHROTTLEPOSE 75 S1_PID_4B_ABSTHROTTLEPOSF 76 S1_PID_4C_CMDTHROTTLEACT 77 S1_PID_4D_TIMERUNMILON 78 S1_PID_4E_TIMESINCECODECLEAR 79 S1_PID_4F_MAXMULTIPLE 80 S1_PID_50_MAX_AIRFLOWMAF 81 S1_PID_51_FUELTYPE 82 S1_PID_52_ETHANOLFUELPCT 83 S1_PID_53_ABSEVAPSYSVAPPRES 84 S1_PID_54_EVAPSYSVAPPRES 85 S1_PID_55_SHORTSECOXYTRIMBANKX 86 S1_PID_56_LONGSECOXYTRIMBANKX 87 S1_PID_57_SHORTSECOXYTRIMBANKX 88 S1_PID_58_LONGSECOXYTRIMBANKX 89 S1_PID_59_FUELRAILABSPRES 90 S1_PID_5A_RELACCELPEDALPOS 91 S1_PID_5B_HYBRBATPACKREMLIFE 92 S1_PID_5C_ENGINEOILTEMP 93 S1_PID_5D_FUELINJECTIONTIMING 94 S1_PID_5E_ENGINEFUELRATE 95 S1_PID_5F_EMISSIONREQ 96 S1_PID_60_PIDSSUPPORTED_61_80 97 S1_PID_61_DEMANDENGTORQPCT 98 S1_PID_62_ACTUALENGTORQPCT 99 S1_PID_63_ENGREFTORQ 100 S1_PID_64_ENGPCTTORQ 101 S1_PID_65_AUXINPUTOUTPUT 102 S1_PID_66_MAFSENSOR 103 S1_PID_67_ENGINECOOLANTTEMP 104 S1_PID_68_INTAKEAIRTEMPSENS 105 S1_PID_69_CMDEGR_EGRERROR 106 S1_PID_6A_CMDDIESELINTAIR 107 S1_PID_6B_EXHAUSTGASTEMP 108 S1_PID_6C_CMDTHROTTLEACTREL 109 S1_PID_6D_FUELPRESCONTRSYS 110 S1_PID_6E_INJPRESCONTRSYS 111 S1_PID_6F_TURBOCOMPRPRES 112 S1_PID_70_BOOSTPRESCNTRL 128 S1_PID_80_PIDSSUPPORTED_81_A0 142 S1_PID_8E_ENGFRICTIONPCTTORQ 160 S1_PID_A0_PIDSSUPPORTED_A1_C0 192 S1_PID_C0_PIDSSUPPORTED_C1_E0",
      .sigs = sigs_2564485392,
    },
    {
      .name = "ParameterID_Service02",
      .address = 0x98DAF110,
      .def_val = "2 S2_PID_02_FREEZEDTC",
      .sigs = sigs_2564485392,
    },
    {
      .name = "S1_PID_03_FuelSystemStatus",
      .address = 0x98DAF110,
      .def_val = "1 OPEN_LOOP_(INSUFF._ENG._TEMP.) 2 CLOSED_LOOP_(OXY_SENS) 4 OPEN_LOOP_(ENG._LOAD,_FUEL_CUT) 8 OPEN_LOOP_(SYSTEM_FAILURE) 16 CLOSED_LOOP_(FEEDBACK_ISSUE)",
      .sigs = sigs_2564485392,
    },
    {
      .name = "S1_PID_12_CmdSecAirStatus",
      .address = 0x98DAF110,
      .def_val = "1 UPSTREAM 2 DOWNSTREAM_CATALYTIC_CONV 4 FROM_OUTSIDE_ATMOSPHERE/OFF 8 PUMP_CMD_ON_FOR_DIAGN.",
      .sigs = sigs_2564485392,
    },
    {
      .name = "S1_PID_1C_OBDStandard",
      .address = 0x98DAF110,
      .def_val = "1 OBD-II_AS_DEFINED_BY_THE_CARB 2 OBD_AS_DEFINED_BY_THE_EPA 3 OBD_AND_OBD-II 4 OBD-I 5 NOT_OBD_COMPLIANT 6 EOBD_(EUROPE) 7 EOBD_AND_OBD-II 8 EOBD_AND_OBD 9 EOBD,_OBD_AND_OBD_II 10 JOBD_(JAPAN) 11 JOBD_AND_OBD_II 12 JOBD_AND_EOBD 13 JOBD,_EOBD,_AND_OBD_II 14 RESERVED 15 RESERVED 16 RESERVED 17 ENG._MANU._DIAG._(EMD) 18 EMD_ENHANCED_(EMD+) 19 HD_OBD-C 20 HD_OBD 21 WWH_OBD 22 RESERVED 23 HD_EOBD-I 24 HD_EOBD-I_N 25 HD_EOBD-II 26 HD_EOBD-II_N 27 RESERVED 28 OBDBR-1 29 OBDBR-2 30 KOBD 31 IOBD_I 32 IOBD_II 33 HD_EOBD-IV 34 RESERVED 35 RESERVED",
      .sigs = sigs_2564485392,
    },
    {
      .name = "S1_PID_51_FuelType",
      .address = 0x98DAF110,
      .def_val = "0 NOT_AVAILABLE 1 GASOLINE 2 METHANOL 3 ETHANOL 4 DIESEL 5 LPG 6 CNG 7 PROPANE 8 ELECTRIC 9 BIFUEL_RUNNING_GASOLINE 10 BIFUEL_RUNNING_METHANOL 11 BIFUEL_RUNNING_ETHANOL 12 BIFUEL_RUNNING_LPG 13 BIFUEL_RUNNING_CNG 14 BIFUEL_RUNNING_PROPANE 15 BIFUEL_RUNNING_ELECTRICITY 16 BIFUEL_ELECTRIC/COMB._ENG. 17 HYBRID_GASOLINE 18 HYBRID_ETHANOL 19 HYBRID_DIESEL 20 HYBRID_ELECTRIC 21 HYBRID_RUNNING_ELECTRIC/COMB. 22 HYBRID_REGENERATIVE 23 BIFUEL_RUNNING_DIESEL",
      .sigs = sigs_2564485392,
    },
    {
      .name = "service",
      .address = 0x98DAF110,
      .def_val = "10 PERMANENT_DTCS_(CLEARED_DTCS) 9 REQUEST_VEHICLE_INFORMATION 8 CONTROL_ON-BOARD_SYSTEM 7 SHOW_PENDING_DTCS 6 OTHER_SYSTEM_MONITORING 5 OXYGEN_SENSOR_MONITORING 4 CLEAR_DTCS_AND_STORED_VALUES 3 SHOW_STORED_DTCS 2 SHOW_FREEZE_FRAME_DATA 1 SHOW_CURRENT_DATA",
      .sigs = sigs_2564485392,
    },
};

}

const DBC CSS_Electronics_OBD2_Extended_1_4 = {
  .name = "CSS_Electronics_OBD2_Extended_1_4",
  .num_msgs = ARRAYSIZE(msgs),
  .msgs = msgs,
  .vals = vals,
  .num_vals = ARRAYSIZE(vals),
};

dbc_init(CSS_Electronics_OBD2_Extended_1_4)